spring:
  application:
    name: karaplan
  http:
    encoding:
      charset: UTF-8
      force: true
  jackson:
    default-property-inclusion: non-empty
  security:
    user:
      name: root
      password: changeit
      roles: USER,ADMIN
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
  compression:
    enabled: true
