spring:
  application:
    name: karaplan
  http:
    encoding:
      charset: UTF-8
      force: true
  jackson:
    default-property-inclusion: non-empty
  jpa:
    generateDdl: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: toComplete
            client-secret: toComplete
server:
  port: 8080
  compression:
    enabled: true
