spring:
  application:
    name: karaplan
  http:
    encoding:
      charset: UTF-8
      force: true
  jackson:
    default-property-inclusion: non-empty
  jpa:
    generateDdl: true
    properties:
      hibernate.globally_quoted_identifiers: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: toComplete
            client-secret: toComplete
server:
  port: 8080
  compression:
    enabled: true
  servlet:
    session:
      timeout: 12h
logging:
  level:
    me.crespel.karaplan: debug
karaplan:
  karafun:
    remote:
      endpoint: https://www.karafun.com
      endpoint-for-locale:
        de: https://www.karafun.de
        en: https://www.karafun.com
        es: https://www.karafun.es
        fr: https://www.karafun.fr
        it: https://www.karafun.it
        nl: https://www.karafun.nl
  kv:
    endpoint: https://www.karaoke-version.com/api
    endpoint-for-locale:
      de: https://www.karaoke-version.de/api
      en: https://www.karaoke-version.com/api
      es: https://www.version-karaoke.es/api
      fr: https://www.version-karaoke.fr/api
      it: https://www.versione-karaoke.it/api
      nl: https://www.karaoke-versie.nl/api
