apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karaplan.fullname" . }}-deployment
  labels:
{{ include "karaplan.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "karaplan.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "karaplan.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: "{{ tpl $key $ }}"
              value: "{{ tpl (print $value) $ }}"
            {{- end }}
          {{- end }}
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ tpl .Values.envFromSecret . }}
          {{- end }}
          startupProbe:
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
