apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karaplan.fullname" . }}-datasource-secret
  labels:
{{ include "karaplan.labels" . | indent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.datasource.username | quote }}
  password: {{ .Values.secrets.datasource.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karaplan.fullname" . }}-google-oauth-secret
  labels:
{{ include "karaplan.labels" . | indent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.secrets.google.clientId | quote }}
  clientSecret: {{ .Values.secrets.google.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karaplan.fullname" . }}-facebook-oauth-secret
  labels:
{{ include "karaplan.labels" . | indent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.secrets.facebook.clientId | quote }}
  clientSecret: {{ .Values.secrets.facebook.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karaplan.fullname" . }}-github-oauth-secret
  labels:
{{ include "karaplan.labels" . | indent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.secrets.github.clientId | quote }}
  clientSecret: {{ .Values.secrets.github.clientSecret | quote }}
