name: CI

on: [push]

env:
  MAVEN_OPTS: -Xms64m -Xmx256m
  MAVEN_CLI_OPTS: -B -Dfrontend-build -Ddocker-build
  MAVEN_GOALS: clean verify
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: fcrespel
  DOCKER_IMAGE: karaplan

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build webapp
      run: mvn ${MAVEN_CLI_OPTS} ${MAVEN_GOALS} -DskipTests
    - name: Test webapp
      run: mvn ${MAVEN_CLI_OPTS} test
    - name: Build image
      run: docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE}:$(basename $GITHUB_REF) target/docker-build
    - name: Publish image
      run: |
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        docker push ${DOCKER_REPO}/${DOCKER_IMAGE}:$(basename $GITHUB_REF)
