name: CI

on: [push]

env:
  MAVEN_OPTS: -Xms64m -Xmx256m
  MAVEN_CLI_OPTS: -s .mvn/settings.xml -B -Dfrontend-build -Ddocker-build
  MAVEN_GOALS: clean verify
  GITHUB_USER: fcrespel
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REPO: fcrespel
  DOCKER_IMAGE: karaplan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build webapp
      run: mvn ${MAVEN_CLI_OPTS} ${MAVEN_GOALS} -DskipTests
    - name: Test webapp
      run: mvn ${MAVEN_CLI_OPTS} test
    - name: Deploy webapp
      if: startsWith(github.ref, 'refs/tags')
      run: mvn ${MAVEN_CLI_OPTS} deploy -DskipTests
    - name: Build image
      run: docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE}:$(basename $GITHUB_REF) target/docker-build
    - name: Publish image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${DOCKER_REPO}/${DOCKER_IMAGE}:$(basename $GITHUB_REF)
